name: Python Tests

# Запускать пайплайн при каждом push в репозиторий
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Виртуальный сервер на Linux
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run Pytest with Coverage
      run: |
        python -m pytest --cov=app --cov-report=term